services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
    command: >
      bash -c "chmod -R 775 storage bootstrap/cache &&
               chown -R www-data:www-data storage bootstrap/cache &&
               apache2-foreground"

  db:
    image: postgres:16
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
